apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-19c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-19c
  template:
    metadata:
      labels:
        app: oracle-19c
        selector: oracle-19c
    spec:
      containers:
      - name: oracle-19c
        image: <your image creation location>
        env:
        - name: ORACLE_SID
          value: <your-sid>
        - name: ORACLE_PDB
          value: <your-portable-db-name>
        - name: ORACLE_EDITION
          value: enterprise
        - name: ORACLE_PWD
          valueFrom:
            secretKeyRef:
              name: oracledb-secret
              key: oracleRootPassword
        resources:
          limits:
            cpu: 1
            memory: 2500Mi
          requests:
            cpu: 1
            memory: 2000Mi
        ports:
        - name: main-port
          containerPort: 1521
        - name: em-port
          containerPort: 5500